### ISSUE TITLE
Implement basic .on() functionality

### ISSUE THREAD

**Issue by marc-costello** [marc-costello/evt#1]
For example:

```
evt('#my-element').on('click', function(e) {
    ...
});
```

That's it. Not worrying about filtering or event grouping. Just the basics

**Comment by marc-costello** [comment]
@richarddowson How is our internal **tree** going to look then?

```
var tree = {
    'namespace/event type' : {
        'elementToken': [
            handler, handler, handler
        ]
    }
}
```

or similar?

**Comment by richarddowson** [comment]
OK, here is the API I was thinking of (incomplete, but for discussion!):

```
var cache = new Cache()

function on(element, eventdescriptor, handler) {
  cache.add(element.token, eventdescriptor, handler);
  if (!cache.contains(eventname, proxyhandler) {
    element.addEventListener(eventname, proxyhandler);
  }
}

function off(element, eventname, handler) {
  var handlersLeft = cache.remove(element.token, eventname, handler);
  if (handlersLeft === 0) {
    element.removeEventListener(eventname, proxyhandler);
  }
}

function proxyhandler(event) {
  var handlers = cache.getHandlers(this.token, event.type)
  handlers.forEach(function(h) {
    h(event);
  });
}
```

**Comment by marc-costello** [comment]
Couple of things:
- This would probably work for the very basic on/off scenario, but if we go down this route now; how easy is it to support filtering and grouping?
- Not sure why we need to pass **element** in? We already wrap the element in the evt object. So (presuming we don't change our direction on this...) .on() and .off() can access the element(s) through this._elements. However, after thinking about it, maybe we should only pass in the token rather than the actual elements. Would mean we have to query for them again like, which isn't as quick, but safer?
- I like the separation `new Cache()` brings.

**Comment by richarddowson** [comment]
Sorry, it was intentionally incomplete; on() and off() are for illustrating the cache API, and would be private normalised versions of the public on() & off() intended to accept a single element and event. evt(element | selector) may apply to multiple elements, .on(eventselector) could also apply multiple events. 

Internally the Cache will store an array of items:

```
{
  elementToken: '92879284792',
  eventname: 'click.namespacename',
  eventtype: 'click',
  namespace: 'namespace',
  eventtarget: selector,
  handler: function,
  enabled: boolean
}
```

Finding items in the cache is then a question of map / reduce. eventtarget is the filter value to be used for delegated events. enabled gives us suspend / resume. The trade off is that using a flat array makes querying simpler compared to an object graph.

**Comment by marc-costello** [comment]
https://github.com/marc-costello/evt/pull/13
