### ISSUE TITLE
Implement basic .off() functionality

### ISSUE THREAD

**Issue by marc-costello** [marc-costello/evt#2]
Remove all event handlers registered on the element. 

```
evt('#my-element').off();
```

_Note: Only remove handlers which have been registered using evt_

**Comment by richarddowson** [comment]
Remove all handlers? Or remove a specific handler  / event? I.e. should the API be:

```
evt(selector).off([string eventName [, function handler]]);
```

**Comment by marc-costello** [comment]
So:
`evt(selector).off();` removes them all.
`evt(selector).off(string eventName);` removes all handlers attached to that name.
`evt(selector).off(string eventName, function handler);` removes that handler only.

Look right?

**Comment by richarddowson** [comment]
Yeah, looks better.

**Comment by marc-costello** [comment]
https://github.com/marc-costello/evt/pull/14
